inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  NewCops: enable

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Naming/FileName:
  Exclude:
    - 'gemfiles/Gemfile.*'

Gemspec/RequireMFA:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false
