# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{page_title_helper}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lukas Westermann"]
  s.date = %q{2010-09-09}
  s.email = %q{lukas.westermann@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION.yml",
     "init.rb",
     "lib/page_title_helper.rb",
     "test/en.yml",
     "test/en_wohaapp.yml",
     "test/multiple_formats_test.rb",
     "test/page_title_helper_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/lwe/page_title_helper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple, internationalized and DRY page titles and headings for rails.}
  s.test_files = [
    "test/multiple_formats_test.rb",
     "test/page_title_helper_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 2.3.0"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.2"])
      s.add_development_dependency(%q<rr>, [">= 0.10.5"])
    else
      s.add_dependency(%q<rails>, [">= 2.3.0"])
      s.add_dependency(%q<shoulda>, [">= 2.10.2"])
      s.add_dependency(%q<rr>, [">= 0.10.5"])
    end
  else
    s.add_dependency(%q<rails>, [">= 2.3.0"])
    s.add_dependency(%q<shoulda>, [">= 2.10.2"])
    s.add_dependency(%q<rr>, [">= 0.10.5"])
  end
end

