---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '15 3 * * 1'
permissions:
  contents: read
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  static-analysis:
    name: 'Static analysis'
    runs-on: ubuntu-26.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@984c0c890880bbf811283d6f09c4607c62d210a4 # v1.323.0
        with:
          ruby-version: '4.0.7'
          bundler-cache: true
      - name: 'Check the environment'
        run: |
          ruby --version
          gem --version
          bundle --version
      - name: 'Run RuboCop'
        run: |
          bundle exec rubocop Gemfile gemfiles/release.gemfile \
            gemfiles/Gemfile.rails-8.0 gemfiles/Gemfile.rails-8.1 \
            lib/ test/ Rakefile

  test:
    name: "Tests: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}"
    runs-on: ubuntu-26.04
    timeout-minutes: 2
    env:
      BUNDLE_GEMFILE: "${{ github.workspace }}/gemfiles/Gemfile.rails-${{ matrix.rails }}"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@984c0c890880bbf811283d6f09c4607c62d210a4 # v1.323.0
        with:
          ruby-version: '${{ matrix.ruby }}'
          bundler-cache: true
      - name: 'Check the environment'
        run: |
          ruby --version
          gem --version
          bundle --version
          echo $BUNDLE_GEMFILE
      - name: 'Run the tests'
        run: 'bundle exec rake --trace test'
    strategy:
      fail-fast: false
      matrix:
        include:
          - { 'rails': '8.0', 'ruby': '3.3.12' }
          - { 'rails': '8.0', 'ruby': '3.4.10' }
          - { 'rails': '8.0', 'ruby': '4.0.7' }
          - { 'rails': '8.1', 'ruby': '3.3.12' }
          - { 'rails': '8.1', 'ruby': '3.4.10' }
          - { 'rails': '8.1', 'ruby': '4.0.7' }

  zizmor:
    name: zizmor

    runs-on: ubuntu-26.04

    timeout-minutes: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
        with:
          advanced-security: false
          persona: auditor
