---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '15 3 * * 1'
permissions:
  contents: read
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  static-analysis:
    name: 'Static analysis'
    runs-on: ubuntu-26.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '4.0.6'
          bundler-cache: true
      - name: 'Check the environment'
        run: |
          ruby --version
          gem --version
          bundle --version
      - name: 'Run RuboCop'
        run: |
          bundle exec rubocop Gemfile \
            gemfiles/Gemfile.rails-8.0 \
            gemfiles/Gemfile.rails-8.1 lib/ test/ Rakefile

  test:
    name: "Tests: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}"
    runs-on: ubuntu-26.04
    timeout-minutes: 2
    env:
      BUNDLE_GEMFILE: "${{ github.workspace }}/gemfiles/Gemfile.rails-${{ matrix.rails }}"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '${{ matrix.ruby }}'
          bundler-cache: true
      - name: 'Check the environment'
        run: |
          ruby --version
          gem --version
          bundle --version
          echo $BUNDLE_GEMFILE
      - name: 'Run the tests'
        run: 'bundle exec rake --trace test'
    strategy:
      fail-fast: false
      matrix:
        include:
          - { 'rails': '8.0', 'ruby': '3.3.12' }
          - { 'rails': '8.0', 'ruby': '3.4.10' }
          - { 'rails': '8.0', 'ruby': '4.0.6' }
          - { 'rails': '8.1', 'ruby': '3.3.12' }
          - { 'rails': '8.1', 'ruby': '3.4.10' }
          - { 'rails': '8.1', 'ruby': '4.0.6' }

  zizmor:
    name: zizmor

    runs-on: ubuntu-26.04

    permissions:
      security-events: read # necessary so that the job can also run after the merge to main

    timeout-minutes: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99 # v0.6.3
        with:
          persona: auditor
