---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '15 3 * * 1'
jobs:
  static-analysis:
    name: 'Static analysis'
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: 'Check the environment'
        run: |
          ruby --version
          gem --version
      - name: 'Install bundler'
        run: |
          gem install bundler
          bundle --version
      - name: 'Install gems'
        run: 'bundle install --jobs 4 --retry 3'
      - name: 'Run RuboCop'
        run: |
          bundle exec rubocop Gemfile \
            gemfiles/Gemfile.rails-5.2 gemfiles/Gemfile.rails-6.0 \
            gemfiles/Gemfile.rails-6.1 gemfiles/Gemfile.rails-7.0 \
            lib/ test/ Rakefile
  test:
    name: "Tests: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}"
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ matrix.ruby }}'
      - name: 'Check the environment'
        run: |
          ruby --version
          gem --version
      - name: 'Install bundler'
        run: |
          gem install bundler
          bundle --version
      - name: 'Install gems'
        env:
          MATRIX_RAILS_VERSION: ${{ matrix.rails }}
        run: |
          export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/Gemfile.rails-${MATRIX_RAILS_VERSION}"
          bundle install --jobs 4 --retry 3
      - name: 'Run the tests'
        run: 'bundle exec rake --trace test'
    strategy:
      fail-fast: false
      matrix:
        include:
          - { 'rails': '5.2', 'ruby': '2.7.8' }
          - { 'rails': '5.2', 'ruby': '3.0.6' }
          - { 'rails': '5.2', 'ruby': '3.1.4' }
          - { 'rails': '5.2', 'ruby': '3.2.2' }
          - { 'rails': '6.0', 'ruby': '2.7.8' }
          - { 'rails': '6.0', 'ruby': '3.0.6' }
          - { 'rails': '6.0', 'ruby': '3.1.4' }
          - { 'rails': '6.0', 'ruby': '3.2.2' }
          - { 'rails': '6.1', 'ruby': '2.7.8' }
          - { 'rails': '6.1', 'ruby': '3.0.6' }
          - { 'rails': '6.1', 'ruby': '3.1.4' }
          - { 'rails': '6.1', 'ruby': '3.2.2' }
          - { 'rails': '7.0', 'ruby': '2.7.8' }
          - { 'rails': '7.0', 'ruby': '3.0.6' }
          - { 'rails': '7.0', 'ruby': '3.1.4' }
          - { 'rails': '7.0', 'ruby': '3.2.2' }
