---
name: 'Push gem'

on:
  push:
    tags:
      - 'v*'

permissions: { }

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  push:
    name: 'Publish to RubyGems'
    runs-on: ubuntu-26.04
    timeout-minutes: 2
    permissions:
      id-token: write # trusted publishing + attestations
    env:
      BUNDLE_GEMFILE: "${{ github.workspace }}/gemfiles/release.gemfile"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@bec3f19a76460dbe12f60def7d1a77585f07516c # v1.322.0
        with:
          ruby-version: '4.0.7'

      - name: 'Publish to RubyGems'
        uses: rubygems/release-gem@7f9650160c1a4e7989fdc9855807bdbd421d8b6b # v1.4.1
